In [45]:
import numpy
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.datasets import imdb
from tensorflow.keras import layers
import matplotlib.pyplot as plt

# Parte 1: Introducción

### Ejercicio 1
Generar un tensor llamado **x** cuyo contenido sea el siguiente:

![Imgur](https://i.imgur.com/rfaKGUG.png)

In [21]:
x = tf.reshape(tf.range(0,60,2), (2, 3, 5))
print(x)

tf.Tensor(
[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]]

 [[30 32 34 36 38]
  [40 42 44 46 48]
  [50 52 54 56 58]]], shape=(2, 3, 5), dtype=int32)


### Ejercicio 2
Realizar los cambios necesarios en los siguientes tensores para que sea posible multiplicar cada columna del tensor "X" por el vector "y".

In [39]:
X = tf.ones((2, 4, 5, 3))
y = tf.constant([1., 2., 3., 4., 5.])

# Code here
#(d1,d2,d3,d) = ()
X = tf.reshape(X,(3,2,4,5))
y = tf.reshape(y,(1,5))
print(X.shape)
print(y.shape)
print("Tensor X:", X)
print("Tensor y:", y)

print(tf.multiply(X, y))



3
5
Tensor X: tf.Tensor(
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]], shape=(3, 2, 4, 5), dtype=float32)
Tensor y: tf.Tensor([[1. 2. 3. 4. 5.]], shape=(1, 5), dtype=float32)
tf.Tensor(
[[[[1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]]

  [[1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]]]


 [[[1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]]

  [[1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]
   [1. 2. 3. 4. 5.]]]


 [[[1. 2. 3. 4. 5.]
   [1. 2. 

### Ejercicio 3
Sobre Tensores, implemente las operaciones Suma, Producto Tensorial y Contraccion Tensorial. Para ello agregue las operaciones tensoriales que sean pertinentes

In [42]:
# Code here
#np.einsum('ij,jk->ik', X, y) Puede ser importante para las operaciones tensoriales
A = tf.reshape(tf.range(0,12), (2, 3, 2))
B = tf.reshape(tf.range(12,24), (2, 3, 2))

#print("Tensor A:", A)
#print("Tensor B:", B)

def suma_tensorial(X,Y):
    if X.shape == Y.shape:
        return X + Y
    else:
        print("Las dimensiones de los tensores no coinciden")
        return None

def broadcast(X,Y):
    size_x = len(X.shape)
    size_y = len(Y.shape)
    Z = np.zeros(size_x)
    if size_x > size_y:
        pass     
    else:
        pass


#print(suma_tensorial(A,B))

def producto_tensorial(X,Y):
    Z = tf.zeros(X.shape + Y.shape)
    
   


Tensor A: tf.Tensor(
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]], shape=(2, 3, 2), dtype=int32)
Tensor B: tf.Tensor(
[[[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[[12 14]
  [16 18]
  [20 22]]

 [[24 26]
  [28 30]
  [32 34]]], shape=(2, 3, 2), dtype=int32)


### Ejercicio 4
Descargar y estudiar el dataset de IMDB de Keras (num_words = 10000)
Separar el dataset en conjuntos de train y test

In [52]:
# Code here
from keras.datasets import imdb
(training_data, training_targets), (testing_data, testing_targets) = imdb.load_data(num_words=10000)

(50000,)
(50000,)


# Ejercicio 5
Dentro del conjunto de Test extraer el primer review positivo y el primer negativo. Hacer la codificacion back-to-text de cada uno de ellos

In [ ]:
# Code here

### Ejercicio 6
Sin hacer uso de las librerias de Keras, crear una red neuronal feed-forward fully_connected con la siguiente arquitectura: capa de entrada - 16 -16 - capa de salida.
(Programar todas las funciones necesarias)


In [ ]:
# Code here

### Ejercicio 7
Tomar un lote random de 100 reviews en el conjunto de train y hacer forward por su red neuronal estimando el error para ese lote. Definir la funcion de error pertinente.

In [ ]:
# Code here

### Ejercicio 8
Usando Keras defina la misma red neuronal anterior

In [ ]:
# Code here

### Ejercicio 9
Entrene el modelo definido usando un batchs de 512 elementos y 20 epoch. Recuerden generar los conjuntos de validacion y train.

In [ ]:
# Code here

### Ejercicio 10
Plotear las curvas de **Training vs Validation Loss** con la loss por cada epochs
Plotear las curvas de **Training vs Validation Accuracy** con el accuracy por cada epochs

Haga un resumen con las conclusiones observadas en ambas graficas

In [ ]:
# Code here